# 2021/12/05 hmaarrfk
# Tensorflow 2.7.0 requires futimens which is only
# available on 10.13
MACOSX_SDK_VERSION:        # [osx and x86_64]
  - "10.13"                # [osx and x86_64]
channel_sources:
  - conda-forge/label/mlir_tf,conda-forge/label/llvm_tf,conda-forge
