# 2021/12/05 hmaarrfk
# Tensorflow 2.7.0 requires futimens which is only
# available on 10.13
MACOSX_DEPLOYMENT_TARGET:  # [osx and x86_64]
  - "10.13"                # [osx and x86_64]
MACOSX_SDK_VERSION:        # [osx and x86_64]
  - "10.13"                # [osx and x86_64]

# Hold back for icu73 migration
# https://github.com/conda-forge/tensorflow-feedstock/pull/337
#libprotobuf:
#- '3.21'
#libabseil:
#- '20230125'
#libgrpc:
#- '1.54'
