github_actions_labels:          # [linux or osx]
- cirun-openstack-cpu-2xlarge   # [linux]
- cirun-macos-m4-large          # [osx]
microarch_level:
- 1
- 3   # [linux and x86_64]
libabseil:
- '20240722'
libgrpc:
- '1.67'
libprotobuf:
- 5.28.3
