{% set version = "1.15.0" %}

{% set pyver = "cp{}{}".format(PY_VER[0], PY_VER[2]) %}
{% set platform = "macosx_10_11_x86_64" %}  # [osx] 
{% set platform = "win_amd64" %}  # [win]
{% set fn = "{}-{}-{}-{}m-{}.whl".format("tensorflow", version, pyver, pyver, platform) %}  # [not linux]
{% set fn = "tensorflow-{{ version }}.tar.gz" %}  # [linux]

package:
  name: tensorflow
  version: {{ version }}

source:
  fn: {{ fn }}
  url: https://github.com/tensorflow/tensorflow/archive/v{{ version }}.tar.gz  # [linux]
  sha256: a5d49c00a175a61da7431a9b289747d62339be9cf37600330ad63b611f7f5dc9  # [linux]
  url: https://pypi.io/packages/{{ pyver }}/t/tensorflow/{{ fn }}  # [not linux]
  sha256: 0a01def34c28298970dc83776dd43877fd59e43fddd8e960d01b6eb849ba9938  # [osx and py==27]
  sha256: 79fbb4a38c6e6417d5eef8ccae00b16053750c5d61092ec7caabe4cea6870dc2  # [osx and py==36]
  sha256: d1694e25887bc0d0c31d6c7d9c92c8bf9e0499085c7e5a9dbaacf675c44027a8  # [osx and py==37]
  sha256: 26b86d32f20dba79da30cb87d67a708678cc6c47f6e596c8783433e282e91f00  # [win and py==36]
  sha256: 1afb2e573fe666eb0dd6a45dbb7679de622a318fcc1fc401fb7819068f2d858b  # [win and py==37]
  patches:
    - patches/0001-add-rt-to-linkopts.patch                                     # [linux]
    - patches/0002-stable-image-rotate-test.patch                               # [linux]
    - patches/0003-relax-tolerence-in-special_math_test.patch                   # [linux]
    - patches/0004-skip-read-only-debugger_cli_common-test.patch                # [linux]
    #- patches/0005-fix-lookup_ops-test.patch                                    # [linux]
    - patches/0006-relax-precision-in-matrix_log_op_test.patch                  # [linux]
    #- patches/0007-Add-init-symbol-names-prefixed-with-an-underscore.patch      # [osx]
    #- patches/0008-Add-alternate-clock_gettime-implementation-for-macOS.patch   # [osx]
    - patches/unbundle_llvm.patch                                               # [linux]

build:
  number: 0
  skip: True  # [not x86_64]
  skip: True  # [win and vc<14]

requirements:
  build:
    - {{ compiler('c') }}       # [linux]
    - {{ compiler('cxx') }}     # [linux]
    - bazel >=0.24.1,<=0.25.2   # [linux]
    - nasm                      # [linux]
  host:
    # conda build requirements
    - python
    - pip
    - setuptools <=39.1.0
    - swig                      # [linux]
    # requirements specified by the package itself
    - absl-py >=0.7.0
    - astor >=0.6.0
    - gast >=0.2.0
    - google-pasta >=0.1.6
    - keras-applications >=1.0.6
    - keras-preprocessing >=1.0.5
    - llvmdev >=9.0.0,<10.0.0    # [linux]
    - zlib                      # [linux]
    - libpng                    # [linux]
    - libcurl                   # [linux]
    - nsync                     # [linux]
    - numpy 1.16.1
    - six >=1.10.0
    - protobuf >=3.6.1
    - termcolor >=1.1.0
    - wrapt >=1.11.1
    - grpcio >=1.8.6
    - wheel >=0.26              # [linux]
    - mock >=2.0.0  # [py==27]
    - backports.weakref >=1.0rc1  # [py==27]
    - enum34 >=1.1.6  # [py==27]
    - tensorflow-estimator >=1.14.0rc0,<1.15.0a0
  run:
    - {{ pin_subpackage('tensorflow-base', exact=True) }}

outputs:
  - name: tensorflow-base
    script: build_pkg.sh  # [linux]
    script: build_pkg_osx.sh  # [osx]
    script: build_pkg.bat  # [win]
    build:
      entry_points:
        - freeze_graph = tensorflow.python.tools.freeze_graph:run_main
        - toco_from_protos = tensorflow.lite.toco.python.toco_from_protos:main
        - tflite_convert = tensorflow.lite.python.tflite_convert:main
        - toco = tensorflow.lite.python.tflite_convert:main
        - saved_model_cli = tensorflow.python.tools.saved_model_cli:main
        - tf_upgrade_v2 = tensorflow.tools.compatibility.tf_upgrade_v2_main:main
        - tensorboard = tensorboard.main:run_main
    requirements:
      # build requirements needs to pick up the compiler run_exports
      build:
        - {{ compiler('c') }}       # [linux]
        - {{ compiler('cxx') }}     # [linux]
      host:
        # conda build requirements
        - python
        - pip
        - setuptools <=39.1.0
        # requirements specified by the package itself
        - absl-py >=0.7.0
        - astor >=0.6.0
        - gast >=0.2.0
        - google-pasta >=0.1.6
        - keras-applications >=1.0.6
        - keras-preprocessing >=1.0.5
        - numpy 1.16.1
        - six >=1.10.0
        - protobuf >=3.6.1
        - termcolor >=1.1.0
        - wrapt >=1.11.1
        - grpcio >=1.8.6
        - wheel >=0.26              # [unix]
        - mock >=2.0.0  # [py==27]
        - backports.weakref >=1.0rc1  # [py==27]
        - enum34 >=1.1.6  # [py==27]
        - tensorflow-estimator >=1.14.0rc0,<1.15.0a0
        # pin
        - zlib                     # [linux]
        - libpng                    # [linux]
        - libcurl                   # [linux]
      run:
        - python
        - absl-py >=0.7.0
        - astor >=0.6.0
        - gast >=0.2.0
        - google-pasta >=0.1.6
        - keras-applications >=1.0.6
        - keras-preprocessing >=1.0.5
        - {{ pin_compatible('numpy') }}  # [linux]
        - numpy >=1.16.1,<2.0.0a0        # [not linux]
        - six >=1.10.0
        - zlib  # [linux]
        - libpng  # [linux]
        - libcurl  # [linux]
        - protobuf >=3.6.1
        - termcolor >=1.1.0
        - wrapt >=1.11.1
        - grpcio >=1.8.6
        - mock >=2.0.0  # [py==27]
        - backports.weakref >=1.0rc1  # [py==27]
        - enum34 >=1.1.6  # [py==27]
        - tensorflow-estimator >=1.14.0rc0,<1.15.0a0
        - tensorboard >=1.14.0,<1.15.0a0
    test:
      imports:
        - tensorflow
      commands:
        - freeze_graph --help
        - saved_model_cli --help
        - tflite_convert --help  # [not win]
        - toco_from_protos --help  # [not win]
        - toco --help  # [not win]

  - name: libtensorflow
    script: cp_libtensorflow.sh  # [unix]
    build:
      skip: true  # [not linux]
    requirements:
      # build requirements needs to pick up the compiler run_exports
      build:
        - {{ compiler('c') }}       # [linux]
        - {{ compiler('cxx') }}     # [linux]
      # host requirements to pick up run_exports
      host:
        - libcurl  # [linux]
        - zlib  # [linux]

    test:
      files:
        - test_c.c
      requires:
        - {{ compiler('c') }}
      commands:
        - test -f $PREFIX/lib/libtensorflow.so  # [not win]
        - $CC -o test_c -L${PREFIX}/lib/ -ltensorflow -I${PREFIX}/include/ test_c.c && ./test_c  # [not win]

  - name: libtensorflow_cc
    script: cp_libtensorflow_cc.sh  # [unix]
    build:
      skip: true  # [not linux]
    requirements:
      # build requirements needs to pick up the compiler run_exports
      build:
        - {{ compiler('c') }}       # [linux]
        - {{ compiler('cxx') }}     # [linux]
      # host requirements to pick up run_exports
      host:
        - libcurl  # [linux]
        - zlib  # [linux]
      run:
        - libprotobuf >=3.6.1,<3.7
        - nsync
    test:
      files:
        - test_cc.cc
      requires:
        - {{ compiler('cxx') }}
      commands:
        - test -f $PREFIX/lib/libtensorflow_cc.so  # [not win]
        - $CXX -std=c++11 -o test_cc -L${PREFIX}/lib/ -ltensorflow_cc -ltensorflow_framework -lrt -I${PREFIX}/include/ test_cc.cc && ./test_cc  # [not win]

about:
  home: http://tensorflow.org/
  license: Apache-2.0
  license_file: LICENSE
  license_family: Apache
  summary: TensorFlow is an open source machine learning framework for everyone.
  description: |
    TensorFlow provides multiple APIs.The lowest level API, TensorFlow Core
    provides you with complete programming control.
    Base package contains only tensorflow, not tensorflow-tensorboard.
  dev_url: https://github.com/tensorflow/tensorflow
  doc_url: https://www.tensorflow.org/get_started/get_started
  doc_source_url: https://github.com/tensorflow/tensorflow/tree/master/tensorflow/docs_src

extra:
  recipe-maintainers:
    - waitingkuo
    - ghego
    - hajapy
    - gilbertfrancois
    - farhantejani
    - njzjz
