{% set version = "2.8.0" %}

package:
  name: libtfkernel_all_kernels
  version: {{ version }}

source:
  url: https://github.com/tensorflow/tensorflow/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 66b953ae7fba61fd78969a2e24e350b26ec116cf2e6a7eb93d02c63939c6f9f7
  patches:
    - patches/0001-loosen-requirements.patch
    - 0002-Use-oneDNN-systemlib.patch

build:
  number: 0
  skip: true  # [win]
  skip: true  # [python_impl == 'pypy']
  string: cuda{{ cuda_compiler_version | replace('.', '') }}h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}  # [cuda_compiler_version != "None"]
  string: cpu_h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}  # [cuda_compiler_version == "None"]
  # These are needed as build/configure dependencies but aren't used in the final product
  ignore_run_exports_from:
    - abseil-cpp
    - grpc-cpp
  run_exports:
    # tensorflow makes no ABI guarantees, need to pin to what we built with
    - libtfkernel_all_kernels {{ version }}

requirements:
  build:
    - python *
    - numpy >=1.21
    - nsync                                  # [build_platform != target_platform]
    - snappy                                 # [build_platform != target_platform]
    - giflib                                 # [build_platform != target_platform]
    - jpeg                                   # [build_platform != target_platform]
    - icu                                    # [build_platform != target_platform]
    - libpng                                 # [build_platform != target_platform]
    - flatbuffers <2.0.6                     # [build_platform != target_platform]
    - onednn                                 # [build_platform != target_platform]
    - onednn-cpu-threadpool                  # [build_platform != target_platform]
    - pybind11                               # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('cuda') }}                 # [cuda_compiler_version != "None"]
    - bazel 4.2.2
    - grpc-cpp
    - libprotobuf
    - nasm
    - sed
    - rsync
    # realpath is not available from the docker image for cuda <= 10.2
    # so we install coreutils here
    - coreutils  # [cuda_compiler_version != "None"]
  host:
    # GPU requirements for CUDA
    - cudnn      # [cuda_compiler_version != "None"]
    - nccl       # [cuda_compiler_version != "None"]
    # conda build requirements
    - zlib
    - libpng
    - libcurl
    - curl         # [win]
    - unzip        # [not win]
    - zip          # [not win]
    - m2-unzip     # [win]
    - m2-zip       # [win]
    - openjdk >=8
    - nsync
    # TF_SYSTEM_LIBS, see usage in
    # https://github.com/tensorflow/tensorflow/blob/v{{ version }}/third_party/systemlibs/syslibs_configure.bzl
    # their versions are specified in
    # https://github.com/tensorflow/tensorflow/blob/v{{ version }}/tensorflow/workspace2.bzl
    # but so far there have been no problems with leaving these
    # unpinned; though some restrictions come in for packages
    # that are also listed as a requirement for the pip_package.
    - abseil-cpp 20210324.2
    - astor
    - cython
    - dill
    - giflib
    - grpc-cpp
    # 2022/04/25 hmaarrfk
    # the latest flatbuffers 2.0.6 seems to have removed a sybmol in a patch release...
    # https://github.com/Qengineering/TensorFlow_Lite_Pose_RPi_64-bits/issues/3#issuecomment-1034799822
    - flatbuffers <2.0.6
    - icu
    - jpeg
    - libpng
    - libprotobuf
    - openssl
    - pybind11
    - sqlite
    - snappy
    - zlib
  run:
    # avoid that people without GPUs needlessly download ~200-300MB
    - __cuda  # [cuda_compiler_version != "None"]

test:
  commands:
    - test -f "${PREFIX}/lib/libtfkernel_all_kernels${SHLIB_EXT}"
    - test -f "${PREFIX}/lib/libtensorflow_framework${SHLIB_EXT}"

about:
  home: http://tensorflow.org/
  license: Apache-2.0
  license_file: LICENSE
  license_family: Apache
  summary: TensorFlow is an end-to-end open source platform for machine learning.
  description: |
    TensorFlow offers multiple levels of abstraction so you can choose the
    right one for your needs. Build and train models by using the high-level
    Keras API, which makes getting started with TensorFlow and machine learning
    easy.
  dev_url: https://github.com/tensorflow/tensorflow
  doc_url: https://www.tensorflow.org/get_started/get_started
  doc_source_url: https://github.com/tensorflow/tensorflow/tree/master/tensorflow/docs_src

extra:
  recipe-maintainers:
    - conda-forge/tensorflow
