package:
  name: tensorflow
  version: "0.10.0rc0"

build:
  number: 0
  #  Google supplies 0.10.0rc0 whl files for:
  # - Linux: Python 2.7, 3.4 and 3.5
  # - OS X: Python 2.7, 3.4 and 3.5
  skip: True  # [win]
  skip: True  # [py26]
  skip: True  # [py33]
  entry_points:
    - tensorboard = tensorflow.tensorboard.tensorboard:main

requirements:
  build:
    - python
    - pip
    - numpy >=1.10.1
    - protobuf ==3.0.0b2
    - six >=1.10.0
    - wheel
  run:
    - python
    - numpy >=1.10.1
    - protobuf ==3.0.0b2
    - six >=1.10.0

test:
  imports:
    # Skip the import test on Linux as wheel file require a more recent
    # version of GLIBC++ than the VM used to build and test package.
    - tensorflow  # [not linux]

about:
  home: http://tensorflow.org/
  license: Apache 2.0
  summary: TensorFlow helps the tensors flow

extra:
  recipe-maintainers:
    - jjhelmus
    - danielfrg
    - waitingkuo
