package:
  name: tensorflow
  version: "1.5.1"

build:
  number: 0
  #  Google supplies whl files on PyPI for:
  # - Linux: Python 2.7, 3.3, 3.4, 3.5 and 3.6
  # - OS X: Python 2.7, 3.5 and 3.6
  # - Win-64: Python 3.5 and 3.6
  skip: True  # [win32]
  skip: True  # [win64 and py<35]
  skip: True  # [osx and py34]
  skip: True  # [py26]
  skip: True  # [py33]

requirements:
  build:
    - python
    - pip
  run:
    - python
    - absl-py >=0.1.6
    - enum34 >=1.1.6  # [py<34]
    - mock >=2.0.0    # [py27]
    - numpy >=1.12.1
    - protobuf >=3.4.0
    - six >=1.10.0
    - tensorboard >=1.5.0,<1.6.0
    - backports.weakref >=1.0rc1

test:
  commands:
    # We need to test tensorboard here to avoid a circular dependency
    # with the tensorboard package
    - tensorboard --help  # [not linux]
  imports:
    # Skip the import test on Linux as wheel file require a more recent
    # version of GLIBC++ than the VM used to build and test package.
    - tensorflow  # [not linux]

about:
  home: http://tensorflow.org/
  license: Apache 2.0
  summary: TensorFlow helps the tensors flow

extra:
  recipe-maintainers:
    - jjhelmus
    - danielfrg
    - waitingkuo
    - ghego
    - hajapy
    - dhirschfeld
    - sdvillal
