{% set version = "1.2.1" %}

package:
  name: tensorflow
  version: {{ version }}

source:
  fn: tensorflow-{{ version }}.tar.gz
  url: https://github.com/tensorflow/tensorflow/archive/v{{ version }}.tar.gz
  sha256: f2baf09b1a9a0500907b4d5cb5473070b3ecede06ed6e8d1096873c91922fb9e
  patches:
    # Add -lrt to the link options list
    # https://github.com/tensorflow/tensorflow/issues/121
    - rt_link_arg.patch  # [linux]

build:
  number: 0
  #  Building from source on Linux, disable all but a single build
  skip: True  # [not linux or not py36]
  entry_points:
    - tensorboard = tensorflow.tensorboard.tensorboard:main

requirements:
  build:
    # conda build requirements
    - bazel >=0.4.5
    - pip
    - python
    - swig
    - unzip
    - zip
    - zlib
    # requirements specified by the package itself
    - wheel >=0.26
    - werkzeug >=0.11.10
    - six >=1.10.0
    - protobuf >=3.2.0
    - numpy 1.11.*
    - mock >=2.0.0      # [py2k]
    - markdown >=2.6.8
    - html5lib ==0.9999999
    - bleach ==1.5.0
    - backports.weakref ==1.0rc1
    - python
    - pip
  run:
    - python
    - werkzeug >=0.11.10
    - six >=1.10.0
    - protobuf >=3.2.0
    - numpy >=1.11.0
    - mock >=2.0.0  # [py2k]
    - markdown >=2.6.8
    - html5lib ==0.9999999
    - bleach ==1.5.0
    - backports.weakref ==1.0rc1

test:
  imports:
    - tensorflow

about:
  home: http://tensorflow.org/
  license: Apache 2.0
  license_family: Apache
  summary: TensorFlow is a machine learning library
  description: |
    TensorFlow provides multiple APIs.The lowest level API, TensorFlow Core
    provides you with complete programming control.
  dev_url: https://github.com/tensorflow/tensorflow
  doc_url: https://www.tensorflow.org/get_started/get_started
  doc_source_url: https://github.com/tensorflow/tensorflow/tree/master/tensorflow/docs_src

extra:
  recipe-maintainers:
    - jjhelmus
    - danielfrg
    - waitingkuo
    - ghego
